### ISSUE TITLE
OCCI/INFRA/CREATE/006 traceback

### ISSUE THREAD

**Issue by jeanparpaillon** [CESNET/pOCCI#8]
Runing this test crashes:

$ ./pOCCI/pOCCI.py -t OCCI/INFRA/CREATE/006
[]
Traceback (most recent call last):
  File "./pOCCI/pOCCI.py", line 177, in <module>
    main(sys.argv[1:])
  File "./pOCCI/pOCCI.py", line 156, in main
    result, err_msg = tests_definitions[test].test()
  File "/home/jean/BA_Projets/git/pOCCI/pOCCI/CORE.py", line 1114, in test
    return INFRA_CREATE_LINK('storage', 'link')
  File "/home/jean/BA_Projets/git/pOCCI/pOCCI/CORE.py", line 1092, in INFRA_CREATE_LINK
    for l in result_links:
UnboundLocalError: local variable 'result_links' referenced before assignment

**Comment by jeanparpaillon** [comment]
Should be fixed in https://github.com/jeanparpaillon/pOCCI/commit/03cfc4143c72c546203a17fedb9b9a14a9c0e513

**Comment by valtri** [comment]
Merged with #1, thanks!
